### ISSUE TITLE
Help spelling error

### ISSUE THREAD

**Issue by guija** [gestevie/candybarcake#1]
There is a little misspelling in the help text. In the description of the -r Argument it says "number of levels of the take, default is 2". I think it should be "cake" instead of "take" (File candybarcake.py
, Line 31) (Siedl found it!).

**Comment by gartenriese2** [comment]
Please fix this!

**Comment by gestevie** [comment]
Thanks for your help! Fixed this horrible issue! Thanks to Siedl, too!

**Comment by guija** [comment]
Thanks for the fast fix!
